---
version: '3'
services:
  db:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ${PWD}/mysql/db:/var/lib/mysql
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ${PWD}/redis:/data
